image: "python:3.9"

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - echo "TODO install test requirements"
    - echo "TODO Trigger tests"
    - bash -c "exit 1"

