image: "python:3.9"

stages:
  - test
  - qualite

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - flake8 formation_indus_ds_avancee tests scripts exposition dags
    - vulture formation_indus_ds_avancee scripts exposition dags --min-confidence 100
    - python -m pytest tests/test_unit
    # Add behave command

qualite:
  stage: qualite
  script:
    - pip install -r requirements.txt && pip install -r requirements_test.txt
    # Add quality command
