image: "python:3.9"

stages:
  - test
  - qualite

include:
  - template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - flake8 formation_indus_ds_avancee tests scripts exposition dags
    - vulture formation_indus_ds_avancee scripts exposition dags --min-confidence 100
    - python -m pytest tests/test_unit
    - behave tests/test_functional/features

qualite:
  stage: qualite
  script:
    - pip install -r requirements.txt && pip install -r requirements_test.txt
    - make tests-unitaires  ## pour calculer le code coverage
    - ./tests/tests_pyramid.sh  ## pour mesurer la pyramide de tests
