image: "python:3.9"

stages:
  - test
  - qualite

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - flake8 formation_indus_ds_avancee tests scripts dags
    - vulture formation_indus_ds_avancee scripts dags --min-confidence 100
    - python -m pytest tests/test_unit
    - behave tests/test_functional/features

qualite:
  stage: qualite
  script:
    - pip install -r requirements.txt && pip install -r requirements_test.txt
    - make tests-unitaires  ## pour calculer le code coverage
    - ./tests/tests_pyramid.sh  ## pour mesurer la pyramide de tests
