stages:
  - generate-tp-instructions
  - move-instructions-to-master
  - test
  - qualite

include:
  - template: Security/SAST.gitlab-ci.yml

pages:
  image: golang:1.17.2
  stage: generate-tp-instructions
  script:
    - go get github.com/googlecodelabs/tools/claat
    - cd TP_instructions && claat export tp*.md && cd ..
    - mkdir .public
    - cp -r TP_instructions/* .public
    - mv .public public
  artifacts:
    paths:
      - public

test:
  image: python:3.9
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - flake8 formation_indus_ds_avancee tests scripts exposition dags
    - vulture formation_indus_ds_avancee scripts exposition dags --min-confidence 100
    - python -m pytest tests/test_unit
    - behave tests/test_functional/features

qualite:
  image: python:3.9
  stage: qualite
  script:
    - pip install -r requirements.txt && pip install -r requirements_test.txt
    - make tests-unitaires  ## pour calculer le code coverage
    - ./tests/tests_pyramid.sh  ## pour mesurer la pyramide de tests

moveinstructionstomaster:
  stage: move-instructions-to-master
  variables:
    GIT_STRATEGY: clone
  script:
    - git fetch # To be able to checkout master
    - git config --global user.email "this-is-the-ci@example.com"
    - git config --global user.name "I'm the CI"
    - mkdir ../tmp
    - rm -rf public # Remove generated instructions
    - cp -r TP_instructions/ ../tmp/TP_instructions
    - git checkout master
    - rm -rf TP_instructions
    - cp -r ../tmp/TP_instructions/ .
    - rm -rf ../tmp
    - echo "Updated on $(date)" >> TP_instructions/update_date.md
    - git add .; git commit -m "Automatic update of instructions from dev";
    - git push -q "https://etoulemonde:${GITLAB_TOKEN_TO_PUSH}@${CI_REPOSITORY_URL#*@}"

